### ISSUE TITLE
현재 접속이 되고있지 않습니다.

### ISSUE THREAD

**Issue by tkqn14** [Lastorder-DC/chatreader-kor#16]
음...그냥 오류인가요?

**Comment by Lastorder-DC** [comment]
https://lastorder.xyz/chatreader-kor/speech.html

저는 정상 접속됩니다. 접속 브라우저/윈도우 버전을 적어주세요

**Comment by yaashin** [comment]
저도 구글크롬에윈도우10인데 안되네요 평소에 잘쓰고있다가 어느순간 구글크롬에서만 안되는

**Comment by tkqn14** [comment]
구글 크롬+윈10입니다

**Comment by Lastorder-DC** [comment]
윈도우 10 + 크롬으로 접속 테스트를 계속 했지만 확인되지 않았습니다.
일단 이슈 닫습니다. 본 서비스는 Github에서 무료 제공하는 Pages 기능을 사용하여 제공되므로 간혹 접속이 불량할수 있습니다.
