### ISSUE TITLE
다른 TTS 목소리 지원 가능할까요?

### ISSUE THREAD

**Issue by SemiR4in** [Lastorder-DC/chatreader-kor#17]
트위치에서 잘 쓰고 있습니다!
혹시 다른 TTS 음성도 쓸 수 있을까요?

브라우저마다 목소리가 다른 것 같습니다.
브라우저에서 지원하는 목소리를 보여주고 선택할 수 있으면 좋겠네요!

**Comment by Lastorder-DC** [comment]
지원이 불가능한것은 아니지만 다른 TTS 목소리를 지원하려면 유료 서비스 가입이 필요합니다.

**Comment by SemiR4in** [comment]
아하! 무료 API를 쓰고계신거였군요.
그럼 괜찮을 것 같습니다!
답변해주셔서 감사합니다
