### ISSUE TITLE
In OBS browser plugin, ('speechSynthesis' in window) is true but actually not work.

### ISSUE THREAD

**Issue by dmc31a42** [Lastorder-DC/chatreader-kor#23]
먼저 좋은 앱 만들어주셔서 감사의 말씀 드립니다.
https://github.com/Lastorder-DC/chatreader-kor/blob/b973df998dbac13949901a6679e584c9e810d464/speech.html#L152

OBS 브라우저 플러그인에서 해당 코드가 true로 나오지만
구글에 찾아보면 OBS browser는 speechSynthesis 지원안한다고 하네요.

**Comment by hyuntoe** [comment]
OBS browser에서 독으로 넣으면(obs browser로 열면)
초기화중 에서 넘어가질 않아요...
채널 변경 버튼은 동작하는 것 같습니다.

**Comment by Lastorder-DC** [comment]
@hyuntoe OBS 브라우저 등 CEF 환경의 경우 별도 내장 TTS 환경이 없어(구글 크롬은 구글 TTS를 지원합니다) 지원하지 않습니다. 크롬 등 브라우저로 따로 열어 사용하시는걸 권장드립니다.

**Comment by hyuntoe** [comment]
예 알겠습니다! 고맙습니다~!!
