### ISSUE TITLE
ㅋㅋㅋ와 같은 자음은 읽을 수 없나요?

### ISSUE THREAD

**Issue by AHNS** [Lastorder-DC/chatreader-kor#32]
사용하는 데 ㅋㅋㅋ 등을 읽어주질 않는 것 같아 문의 드립니다

**Comment by Lastorder-DC** [comment]
크롬 이외 브라우저에서 사용시 OS 기본 TTS가 사용되는데, 이경우 `ㅋㅋㅋ`등을 읽지 않을 수 있습니다.

**Comment by Lastorder-DC** [comment]
수정되었습니다.
