### ISSUE TITLE
ChattyCathy.js 접근이 안되는 듯 합니다.

### ISSUE THREAD

**Issue by trustkim** [Lastorder-DC/chatreader-kor#35]
https://chattykathy.lastorder.tk/ChattyKathy.js
이거 때문에 정상 작동 안하는 듯한 이슈가 있는듯하여 남깁니다.

**Comment by trustkim** [comment]
접속하려하면 DNS_PROBE_FINISHED_NXDOMAIN 에러가 뜨네요.
제가 문제인건지 정확하게 모르겠어요.

**Comment by Lastorder-DC** [comment]
저는 정상 동작합니다만 추후 문제를 예방하기 위해 주소를 변경했습니다.
