### ISSUE TITLE
AWS Polly 연동 시 채팅 로그 미표시 문제

### ISSUE THREAD

**Issue by FelisCatusKR** [Lastorder-DC/chatreader-kor#37]
안녕하세요 저는 트위치에서 방송을 하고 있는 스트리머 워나힐입니다. 먼저

좋은 툴 만들어주셔서 감사합니다. 리듬게임 방송하면서 항상 TTS 감사히 사용하고 있습니다.

오늘 Polly 연동을 시도해 보았는데, 연동 자체는 잘 되어 채팅이 읽히는 것은 확인하였으나 Polly를 사용하지 않을 때와는 다르게 페이지 내에 채팅 로그가 뜨지 않습니다.
기존에 블랙리스트 추가를 커맨드 사용 없이 채팅 로그 단축 버튼을 통해 이용하는 입장에서, 채팅 로그가 뜨지 않는 점이 살짝 아쉽습니다. 혹시 Polly 사용 시에도 채팅 로그를 조회할 수 있도록 수정이 가능할까요?

**Comment by Lastorder-DC** [comment]
수정되었습니다.
