### ISSUE TITLE
크롬에서는 제대로 작동되는데

### ISSUE THREAD

**Issue by Lastorder-DC** [Lastorder-DC/chatreader-kor#64]
### Discussed in https://github.com/Lastorder-DC/chatreader-kor/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **girinsujang** March 29, 2022</sup>
엣지에서는 제대로 작동이 안 되네요

목소리도 다르고 일본어도 안 읽어주고

어떻게 해결 방법 없을까요?</div>

**Comment by Lastorder-DC** [comment]
엣지에서도 클라우드 기반 TTS 엔진을 사용하도록 수정했습니다.

**Comment by girinsujang** [comment]
업뎃? 되고 나서는 아예 한글로도 안 읽어줍니다...

**Comment by Lastorder-DC** [comment]
@girinsujang 크롬/엣지/웨일 환경에서 정상 동작하는것을 확인했습니다. 로그아웃-로그인후 다시 시도해 보신뒤 그래도 안된다면 새 이슈 여시면서 사용 환경(윈도우 버전, 사용 브라우저)을 남겨주시면 체크해보겠습니다.
