### ISSUE TITLE
엣지에서는 여전히 작동 안 됨

### ISSUE THREAD

**Issue by girinsujang** [Lastorder-DC/chatreader-kor#66]
![image](https://user-images.githubusercontent.com/83007358/162599683-a4fba433-fd7a-415f-bc49-7f3bff53154a.png)

![image](https://user-images.githubusercontent.com/83007358/162599712-6fc59e30-5245-475c-9656-53ef9662121a.png)

전에도 썼듯이 크롬에서는 잘 되는데 어째선지 엣지나 다른 브라우저에서는 안 되네요..

!!tts voice 이거 써서 디폴트나 폴리로 바꾸어 보아도 안 되네요

**Comment by Lastorder-DC** [comment]
https://youtu.be/mPhHk14EoXk

윈도우 10 Home 21H2 + MS Edge 100.0.1185.36 버전에서 정상적으로 동작하는것을 확인했습니다. 문제를 재현할수 없는 경우 수정도 불가능하니 양해 부탁드립니다.

**Comment by girinsujang** [comment]
계속 귀찮게 해드려서 죄송합니다. 이것저것 만지다 보니 소리는 이제 나오게 됐는데 엣지랑 크롬이랑 목소리가 다릅니다. 이건 브라우저 차이라 어쩔 수 없는 부분인 것이 맞지요? 목소리만 다르면 상관이 없겠는데 읽어주는 것도 미묘하게 다른 느낌이 들어서요

**Comment by Lastorder-DC** [comment]
@girinsujang 네. 크롬과 엣지는 TTS 엔진이 달라서 어쩔수 없습니다. 특히 자체 테스트결과 크롬과 달리 엣지는 피치나 속도등을 변경해도 잘 반영되지 않았는데, 이건 엣지가 사용하는 TTS 서버쪽 문제라 어쩔수 없습니다.

일치시킬수 있는 방법이 없는건 아닙니다. 구글이나 MS 모두 TTS API를 제공하므로 둘중 하나를 사용하면 되긴 합니다만... 브라우저 내장 TTS와 달리 유료라서 비용이 발생됩니다.
